### ISSUE TITLE
The generated config.yml contains tabs causing bukkit config reader errors

### ISSUE THREAD

**Issue by krisdb2009** [d03n3rfr1tz3/Bukkit.JSONAPI#4]
https://github.com/d03n3rfr1tz3/Bukkit.JSONAPI/blob/master/src/resources/config.yml
On line 34 and onword...

**Comment by krisdb2009** [comment]
These tabs just need to be replaced with 4 spaces... (obviously)
Easy fix

**Comment by d03n3rfr1tz3** [comment]
Ups... maybe I should not have used notepad++ for that one change there. Should be fixed in the next release.
@8326d6a663e41e731b418cf230e67ca80c11dc0c

**Comment by krisdb2009** [comment]
Thanks!
