### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX

### ISSUE THREAD

**Issue by JohOply** [d03n3rfr1tz3/Bukkit.JSONAPI#5]
Hi,

I have this error when my server start :) There is also an error with the number of the version (plugin say me 1.0.0)

> [16:30:06 WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> [16:30:06 WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
> [16:30:06 WARN]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
> [16:30:06 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
> [16:30:06 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
> [16:30:06 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
> [16:30:06 WARN]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
> [16:30:06 WARN]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
> [16:30:06 WARN]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
> [16:30:06 WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
> [16:30:06 WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
> [16:30:06 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
> [16:30:06 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
> [16:30:06 WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
> [16:30:06 WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> [16:30:06 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
> [16:30:06 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
> [16:30:06 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> [16:30:06 WARN]: at java.net.URL.openStream(URL.java:1038)
> [16:30:06 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:129)
> [16:30:06 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:107)
> [16:30:06 WARN]: at java.lang.Thread.run(Thread.java:745)
> [16:30:06 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> [16:30:06 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
> [16:30:06 WARN]: at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
> [16:30:06 WARN]: at sun.security.validator.Validator.validate(Validator.java:260)
> [16:30:06 WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
> [16:30:06 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
> [16:30:06 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
> [16:30:06 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
> [16:30:06 WARN]: ... 16 more
> [16:30:06 WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> [16:30:06 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
> [16:30:06 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
> [16:30:06 WARN]: at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
> [16:30:06 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
> [16:30:06 WARN]: ... 22 more

**Comment by frdmn** [comment]
Check https://github.com/alecgorge/jsonapi/issues/442
